name: distgen-impact-cu-inj-ex
channels:
  - conda-forge
dependencies:
  - Python=3.9
  - numpy
  - prefect[kubernetes]
  - scikit-image
  - lume-impact
  - lume-model
  - distgen
  - pandas
  - pip
  - pip:
    - git+https://github.com/jacquelinegarrahan/lume-orchestration-demo.git